# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on: [push]

jobs:
  dotnetpack_nugetpush_job:
    runs-on: ubuntu-latest

    env:
      projectpath: ./pisonet.csproj
      buildconfiguration: release
      outputpath: pisonetout
      runid: ${{github.run_id}}
      githubtoken: ${{ secrets.GITHUB_TOKEN }}
      githubnugetpackageregistry: https://nuget.pkg.github.com/qqacedd/index.json

    permissions:
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ${projectpath}
    - name: Build with dotnet
      run: dotnet build ${projectpath} --configuration ${buildconfiguration} --version-suffix ${runid} --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack as nuget with dotnet
      run: dotnet pack ${projectpath} --configuration ${buildconfiguration} --output ${outputpath} --version-suffix ${runid} --no-build --no-restore
    - name: Publish Nuget to GitHub registry
      run: dotnet nuget push ${outputpath}/*.nupkg --api-key ${githubtoken} --source ${githubnugetpackageregistry} --skip-duplicate --no-symbols true
